package Latte.Absyn; // Java Package generated by the BNF Converter.

public class Arr extends Type {
  public final Type type_;
  public Arr(Type p1) { type_ = p1; }

  public <R,A> R accept(Latte.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.Arr) {
      Latte.Absyn.Arr x = (Latte.Absyn.Arr)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }


}
