package Latte.Absyn; // Java Package generated by the BNF Converter.

public class ArrAcc extends ArrAccess {
  public final LValue lvalue_;
  public final Expr expr_;
  public ArrAcc(LValue p1, Expr p2) { lvalue_ = p1; expr_ = p2; }

  public <R,A> R accept(Latte.Absyn.ArrAccess.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.ArrAcc) {
      Latte.Absyn.ArrAcc x = (Latte.Absyn.ArrAcc)o;
      return this.lvalue_.equals(x.lvalue_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.lvalue_.hashCode())+this.expr_.hashCode();
  }


}
