package Latte.Absyn; // Java Package generated by the BNF Converter.

public class AttrAcc extends AttrAccess {
  public final LValue lvalue_;
  public final String ident_;
  public AttrAcc(LValue p1, String p2) { lvalue_ = p1; ident_ = p2; }

  public <R,A> R accept(Latte.Absyn.AttrAccess.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.AttrAcc) {
      Latte.Absyn.AttrAcc x = (Latte.Absyn.AttrAcc)o;
      return this.lvalue_.equals(x.lvalue_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.lvalue_.hashCode())+this.ident_.hashCode();
  }


}
