package Latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassDef extends TopDef {
  public final String ident_;
  public final ClassBody classbody_;
  public ClassDef(String p1, ClassBody p2) { ident_ = p1; classbody_ = p2; }

  public <R,A> R accept(Latte.Absyn.TopDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.ClassDef) {
      Latte.Absyn.ClassDef x = (Latte.Absyn.ClassDef)o;
      return this.ident_.equals(x.ident_) && this.classbody_.equals(x.classbody_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.classbody_.hashCode();
  }


}
