package Latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassDefE extends TopDef {
  public final String ident_1, ident_2;
  public final ClassBody classbody_;
  public ClassDefE(String p1, String p2, ClassBody p3) { ident_1 = p1; ident_2 = p2; classbody_ = p3; }

  public <R,A> R accept(Latte.Absyn.TopDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.ClassDefE) {
      Latte.Absyn.ClassDefE x = (Latte.Absyn.ClassDefE)o;
      return this.ident_1.equals(x.ident_1) && this.ident_2.equals(x.ident_2) && this.classbody_.equals(x.classbody_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_1.hashCode())+this.ident_2.hashCode())+this.classbody_.hashCode();
  }


}
