package Latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassBlock extends ClassBody {
  public final ListClassElem listclasselem_;
  public ClassBlock(ListClassElem p1) { listclasselem_ = p1; }

  public <R,A> R accept(Latte.Absyn.ClassBody.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.ClassBlock) {
      Latte.Absyn.ClassBlock x = (Latte.Absyn.ClassBlock)o;
      return this.listclasselem_.equals(x.listclasselem_);
    }
    return false;
  }

  public int hashCode() {
    return this.listclasselem_.hashCode();
  }


}
