package Latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassMeth extends ClassElem {
  public final FuncDef funcdef_;
  public ClassMeth(FuncDef p1) { funcdef_ = p1; }

  public <R,A> R accept(Latte.Absyn.ClassElem.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.ClassMeth) {
      Latte.Absyn.ClassMeth x = (Latte.Absyn.ClassMeth)o;
      return this.funcdef_.equals(x.funcdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.funcdef_.hashCode();
  }


}
