package Latte.Absyn; // Java Package generated by the BNF Converter.

public class EApp extends Expr {
  public final FunctionCall functioncall_;
  public EApp(FunctionCall p1) { functioncall_ = p1; }

  public <R,A> R accept(Latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.EApp) {
      Latte.Absyn.EApp x = (Latte.Absyn.EApp)o;
      return this.functioncall_.equals(x.functioncall_);
    }
    return false;
  }

  public int hashCode() {
    return this.functioncall_.hashCode();
  }


}
