package Latte.Absyn; // Java Package generated by the BNF Converter.

public class EAttrAccess extends Expr {
  public final AttrAccess attraccess_;
  public EAttrAccess(AttrAccess p1) { attraccess_ = p1; }

  public <R,A> R accept(Latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.EAttrAccess) {
      Latte.Absyn.EAttrAccess x = (Latte.Absyn.EAttrAccess)o;
      return this.attraccess_.equals(x.attraccess_);
    }
    return false;
  }

  public int hashCode() {
    return this.attraccess_.hashCode();
  }


}
