package Latte.Absyn; // Java Package generated by the BNF Converter.

public class ECastNull extends Expr {
  public final Type type_;
  public ECastNull(Type p1) { type_ = p1; }

  public <R,A> R accept(Latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.ECastNull) {
      Latte.Absyn.ECastNull x = (Latte.Absyn.ECastNull)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }


}
