package Latte.Absyn; // Java Package generated by the BNF Converter.

public class EMthCall extends Expr {
  public final MethodCall methodcall_;
  public EMthCall(MethodCall p1) { methodcall_ = p1; }

  public <R,A> R accept(Latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.EMthCall) {
      Latte.Absyn.EMthCall x = (Latte.Absyn.EMthCall)o;
      return this.methodcall_.equals(x.methodcall_);
    }
    return false;
  }

  public int hashCode() {
    return this.methodcall_.hashCode();
  }


}
