package Latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Expr implements java.io.Serializable {
  public abstract <R,A> R accept(Expr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Latte.Absyn.ECastNull p, A arg);
    public R visit(Latte.Absyn.EAttrAccess p, A arg);
    public R visit(Latte.Absyn.EMthCall p, A arg);
    public R visit(Latte.Absyn.EArrAccess p, A arg);
    public R visit(Latte.Absyn.EVar p, A arg);
    public R visit(Latte.Absyn.ENewArr p, A arg);
    public R visit(Latte.Absyn.ENew p, A arg);
    public R visit(Latte.Absyn.ELitInt p, A arg);
    public R visit(Latte.Absyn.ELitTrue p, A arg);
    public R visit(Latte.Absyn.ELitFalse p, A arg);
    public R visit(Latte.Absyn.EApp p, A arg);
    public R visit(Latte.Absyn.EString p, A arg);
    public R visit(Latte.Absyn.Neg p, A arg);
    public R visit(Latte.Absyn.Not p, A arg);
    public R visit(Latte.Absyn.EMul p, A arg);
    public R visit(Latte.Absyn.EAdd p, A arg);
    public R visit(Latte.Absyn.ERel p, A arg);
    public R visit(Latte.Absyn.EAnd p, A arg);
    public R visit(Latte.Absyn.EOr p, A arg);

  }

}
