package Latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class FunctionCall implements java.io.Serializable {
  public abstract <R,A> R accept(FunctionCall.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Latte.Absyn.FCall p, A arg);

  }

}
