package Latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class FuncDef implements java.io.Serializable {
  public abstract <R,A> R accept(FuncDef.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Latte.Absyn.FunDef p, A arg);

  }

}
