package Latte.Absyn; // Java Package generated by the BNF Converter.

public class Incr extends Stmt {
  public final LValue lvalue_;
  public Incr(LValue p1) { lvalue_ = p1; }

  public <R,A> R accept(Latte.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.Incr) {
      Latte.Absyn.Incr x = (Latte.Absyn.Incr)o;
      return this.lvalue_.equals(x.lvalue_);
    }
    return false;
  }

  public int hashCode() {
    return this.lvalue_.hashCode();
  }


}
