package Latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class LValue implements java.io.Serializable {
  public abstract <R,A> R accept(LValue.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Latte.Absyn.LVFCall p, A arg);
    public R visit(Latte.Absyn.LVMethodCall p, A arg);
    public R visit(Latte.Absyn.LVSimpleIdent p, A arg);
    public R visit(Latte.Absyn.LVEArrAccess p, A arg);
    public R visit(Latte.Absyn.LVAttrAcc p, A arg);

  }

}
