package Latte.Absyn; // Java Package generated by the BNF Converter.

public class LVSimpleIdent extends LValue {
  public final String ident_;
  public LVSimpleIdent(String p1) { ident_ = p1; }

  public <R,A> R accept(Latte.Absyn.LValue.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.LVSimpleIdent) {
      Latte.Absyn.LVSimpleIdent x = (Latte.Absyn.LVSimpleIdent)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
