package Latte.Absyn; // Java Package generated by the BNF Converter.

public class MCall extends MethodCall {
  public final LValue lvalue_;
  public final FunctionCall functioncall_;
  public MCall(LValue p1, FunctionCall p2) { lvalue_ = p1; functioncall_ = p2; }

  public <R,A> R accept(Latte.Absyn.MethodCall.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.MCall) {
      Latte.Absyn.MCall x = (Latte.Absyn.MCall)o;
      return this.lvalue_.equals(x.lvalue_) && this.functioncall_.equals(x.functioncall_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.lvalue_.hashCode())+this.functioncall_.hashCode();
  }


}
