package Latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Latte.Absyn.Arr p, A arg);
    public R visit(Latte.Absyn.Int p, A arg);
    public R visit(Latte.Absyn.Str p, A arg);
    public R visit(Latte.Absyn.Bool p, A arg);
    public R visit(Latte.Absyn.Void p, A arg);
    public R visit(Latte.Absyn.Obj p, A arg);

  }

}
